### ISSUE TITLE
Notes for 2016-09-15 morning

### ISSUE THREAD

**Issue by cathywu** [mehtank/sumosims#55]
## Todo
- [x] Review the PR (new sweeps and new controllers!).
- [ ] Take a look at the TrafficJam plots from `vtype_traffic_jam.py`: https://www.dropbox.com/sh/0skbb3ij4ee30j1/AACQPqWRNXBdGHHM3jafsdXqa?dl=0. Seems promising in terms of energy. Our controllers are in general more efficient than IDM. The human behavior is very efficient but also very slow.
- [ ] Create a more massive human jam.
  - We should be able to recreate the [Japanese (Sugiyama) loop road backwards propagating waves](https://www.youtube.com/watch?v=Suugn-p5C1M). This will serve as the baseline for the experiments. Maybe all of our experiments can be based on these parameters (230 meter loop, 22 vehicles).
  - [ ] I've set up the single-lane version (see `sugiyama_jam.py`); can you confirm that there are backwards propagating waves?
  - Here are plots for various controllers: https://www.dropbox.com/sh/gtyd3wsul26e75v/AABl6rSOMQPpWU32s0yTL4xAa?dl=0. Summary: IDM and ACC do worse than humans; Midpoint does slightly better. This is mostly good news!
- [ ] Relatedly, in the speed profile, can we also plot the 25th and 75th percentile speeds? This may help us determine if the following figure, for example, has backwards propagating waves:
  ![loopsim-230m1l-human022-sugiyamajam](https://cloud.githubusercontent.com/assets/329117/18545253/2650bd8a-7aed-11e6-9198-4de8af983610.png)
- [ ] Let's set up the 2-lane version of the Sugiyama Jam. The experiment is in `sugiyama_jam.py`. When I set `numLanes=2`, I get collisions errors in initializing the cars. Are they all being initialized on the same lane or something? Sample errors:

```
Warning: Vehicle 'human-001' performs emergency stop at the end of lane 'top_0' for unknown reasons (decel=0.00), time=0.00.
Warning: Teleporting vehicle 'human-005'; collision with vehicle 'human-000', lane='right_0', gap=-0.10, time=0.00 stage=move.
Warning: Vehicle 'human-005' ends teleporting on edge 'top', time 0.00.
```
- [ ] Plot the 2-lane behavior of the Sugiyama setting for each of our controllers, similarly to what I did above with the 1-lane version.
- [ ] Tweak the lane changing behavior for the human agents, which results in more instability. Based on what I've seen so far, I expect/hope that the controllers (fillgapmidpoint, in particular, and perhaps also midpoint) will be able to smooth out some of this instability. Fingers crossed.
- [ ] Then experiment with a small number of non-human controllers (similar to `few_robots_sweep.py`), with the total still adding up to `22*numLanes`. Unfortunately, based on what I've seen so far, I don't expect this "few robots" experiment to yield good results. I think we need a good fraction of the vehicles to be controlled in order to achieve a speed increase, for instance. I have not examined the effect on energy though, so that could still be a positive result.
## Questions
- [x] What is the purpose of the color scale on plots in the lower right-hand corner? See example below.
- [x] Do we have different colors for different vehicle types? Also see example below (all points appear red).
- [ ] The energy plots are for all vehicles, not just robot ones, right?

![loopsim-1000m2l-fillgapmidpoint110-trafficjam](https://cloud.githubusercontent.com/assets/329117/18543891/f954f13a-7ae6-11e6-95aa-6f37ae960e29.png)
